# Generated by Django 6.0.1 on 2026-01-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('jd', models.TextField(blank=True)),
                ('jd_file', models.FileField(blank=True, null=True, upload_to='jd_files/')),
                ('room_number', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('venue', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'VENUE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.location')),
            ],
        ),
    ]
