# Generated by Django 6.0.1 on 2026-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("CANTEEN", "Canteen"),
                            ("LIBRARY", "Library"),
                            ("TOILET", "Toilet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("block", models.CharField(max_length=10)),
                ("floor", models.IntegerField()),
                ("room_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
