# Generated by Django 6.0.1 on 2026-01-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('ENTRY', 'Entry Point'), ('VENUE', 'Venue / Hall'), ('TOILET_MEN', 'Toilet (Men)'), ('TOILET_WOMEN', 'Toilet (Women)'), ('CANTEEN', 'Canteen'), ('LIBRARY', 'Library'), ('PRINCIPAL', 'Principal Cabin'), ('DIRECTOR', 'Director Cabin'), ('HOD', 'HOD Cabin'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.TextField()),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='navigation.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='navigation.location')),
            ],
        ),
    ]
